export const IMPORT_STATUSES = ["PREVIEW", "READY", "IMPORTING", "COMPLETED", "FAILED"] as const;
export const IMPORT_ROW_STATUSES = ["VALID", "INVALID", "DUPLICATE_IN_FILE", "DUPLICATE_IN_DATABASE", "IMPORTED"] as const;
export const CAMPAIGN_TARGET_STATUSES = ["WAITING", "READY", "QUEUED", "PROCESSING", "MESSAGE_SENT", "WAITING_REPLY", "REPLIED", "LEAD", "HANDOFF", "REJECTED", "ERROR", "SKIPPED"] as const;
export const OUTREACH_SKIP_REASONS = ["EXISTING_ZAPIS_CLIENT", "MISSING_PHONE", "MANUALLY_EXCLUDED"] as const;
export const WHATSAPP_CONNECTION_STATUSES = ["DISABLED", "IDLE", "STARTING", "QR_REQUIRED", "AUTHENTICATING", "CONNECTED", "DISCONNECTING", "LOGGING_OUT", "ERROR"] as const;
export const WHATSAPP_MESSAGE_STATUSES = ["PENDING", "OUTCOME_UNKNOWN", "SENT", "DELIVERED", "READ", "RECEIVED", "FAILED"] as const;

export type CampaignTargetStatus = typeof CAMPAIGN_TARGET_STATUSES[number];
export type WhatsAppConnectionStatus = typeof WHATSAPP_CONNECTION_STATUSES[number];
export type WhatsAppMessageStatus = typeof WHATSAPP_MESSAGE_STATUSES[number];
