"use client";
/* eslint-disable @next/next/no-location-assign-relative-destination */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Archive, Eye, Pencil, Plus, RefreshCw } from "lucide-react";
import { api, ApiError, unpackList } from "@/src/lib/api/client";
import { Button, EmptyState, ErrorState, LoadingState, Modal, Pagination, SearchInput, SelectFilter, StatusBadge } from "@/src/components/ui/ui";
import { dateTime } from "@/src/lib/formatters";
import { ContactForm } from "./contact-form";
import { Contact, CONTACT_STATUSES, ContactStatus, contactLabel } from "./types";

export function ContactsPage() {
  const [rows,setRows]=useState<Contact[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(1); const [limit,setLimit]=useState(20);
  const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState("");
  const [stats,setStats]=useState<Record<string,number>>({}); const [editing,setEditing]=useState<Contact|null|undefined>(undefined); const [archiving,setArchiving]=useState<Contact|null>(null); const [archiveBusy,setArchiveBusy]=useState(false);
  const load = useCallback(async (background=false) => { if(background)setRefreshing(true);else setLoading(true); setError(""); try { const payload=await api.get<unknown>("/contacts",{query:{page,limit,search,status}}); const list=unpackList<Contact>(payload); setRows(list.items); setTotal(list.total); } catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить контакты");} finally{setLoading(false);setRefreshing(false)} },[page,limit,search,status]);
  useEffect(()=>{const timer=setTimeout(()=>load(false),search?350:0);return()=>clearTimeout(timer)},[load,search]);
  useEffect(()=>{Promise.all(["",...CONTACT_STATUSES].map(value=>api.get<unknown>("/contacts",{query:{page:1,limit:1,status:value}}).then(p=>unpackList<Contact>(p).total))).then(values=>setStats(Object.fromEntries(["TOTAL",...CONTACT_STATUSES].map((key,i)=>[key,values[i]])))).catch(()=>{});},[]);
  async function archive(){if(!archiving)return;setArchiveBusy(true);try{await api.delete(`/contacts/${archiving.id}`);setArchiving(null);await load(true);}catch(e){setError(e instanceof ApiError?e.message:"Не удалось переместить контакт в архив");}finally{setArchiveBusy(false)}}
  if(loading&&!rows.length&&!error)return <LoadingState/>;
  return <section className="page contacts-page">
    <div className="contacts-title"><div><h2>Контакты</h2><p>База компаний для автоматической работы AI-продавца</p></div><div><Link className="button secondary" href="/contacts/deleted"><Archive size={15}/>Архив</Link><Button onClick={()=>setEditing(null)}><Plus size={15}/>Добавить контакт</Button></div></div>
    <div className="contact-stats">{[["TOTAL","Всего"],["NEW","Новые"],["IN_PROGRESS","В работе"],["QUALIFIED","Квалифицированы"],["REJECTED","Исключены"]].map(([key,label])=><div key={key}><span>{label}</span><strong>{stats[key]??"—"}</strong></div>)}</div>
    <div className="toolbar"><SearchInput placeholder="Компания, телефон, город, email…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><SelectFilter label="Статус" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Все</option>{CONTACT_STATUSES.map(value=><option key={value} value={value}>{contactLabel(value)}</option>)}</SelectFilter><SelectFilter label="Строк" value={limit} onChange={e=>{setLimit(Number(e.target.value));setPage(1)}}>{[20,50,100].map(v=><option key={v}>{v}</option>)}</SelectFilter><Button variant="secondary" loading={refreshing} onClick={()=>load(true)}><RefreshCw size={15}/>Обновить</Button></div>
    {error&&<ErrorState message={error} retry={()=>load(false)}/>} {!error&&(!rows.length?<EmptyState title="Контакты не найдены" description="Измените параметры поиска или добавьте первый контакт."/>:<><div className="table-wrap contact-table"><table><thead><tr><th>Компания</th><th>Телефон</th><th>Город</th><th>Тип бизнеса</th><th>CRM</th><th>Стратегия</th><th>Статус</th><th>Обработка</th><th>Дата</th><th>Действия</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><Link href={`/contacts/${c.id}`}>{c.companyName}</Link></td><td>{c.phone}</td><td>{c.city||"—"}</td><td>{contactLabel(c.businessType)}</td><td><StatusBadge>{contactLabel(c.crmProvider,"Не определена")}</StatusBadge></td><td>{contactLabel(c.strategyCode,"Стратегия не определена")}</td><td><StatusBadge tone={statusTone(c.status)}>{contactLabel(c.status)}</StatusBadge></td><td><StatusBadge tone={c.outreachEligible?"success":"danger"}>{c.outreachEligible?"Можно":"Не обрабатывать"}</StatusBadge></td><td>{dateTime(c.createdAt)}</td><td><div className="row-actions"><Link href={`/contacts/${c.id}`} aria-label="Открыть"><Eye size={16}/></Link><button onClick={()=>setEditing(c)} aria-label="Изменить"><Pencil size={16}/></button><button onClick={()=>setArchiving(c)} aria-label="В архив"><Archive size={16}/></button></div></td></tr>)}</tbody></table></div><Pagination page={page} total={total} limit={limit} onChange={setPage}/></>)}
    <ContactForm key={editing===undefined?"closed":editing?.id||"new"} open={editing!==undefined} contact={editing} onClose={()=>setEditing(undefined)} onSaved={saved=>{setEditing(undefined);window.location.href=`/contacts/${saved.id}`}}/>
    <Modal open={!!archiving} title="Переместить контакт в архив?" onClose={()=>!archiveBusy&&setArchiving(null)}><p>Контакт перестанет участвовать в новых кампаниях и AI-обработке. История переписки и лидов сохранится.</p><div className="form-actions"><Button variant="secondary" onClick={()=>setArchiving(null)} disabled={archiveBusy}>Отмена</Button><Button variant="danger" loading={archiveBusy} onClick={archive}>В архив</Button></div></Modal>
  </section>;
}
function statusTone(status:ContactStatus):"success"|"danger"|"warning"|"info" {return status==="QUALIFIED"?"success":status==="REJECTED"||status==="ERROR"?"danger":status==="IN_PROGRESS"?"warning":"info"}
