"use client";

import { Bell, Bot, ExternalLink, MessageCircle, RefreshCw, RotateCcw, Send, Unplug, UserRoundPlus } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, ApiError, unpackList } from "@/src/lib/api/client";
import { dateTime } from "@/src/lib/formatters";
import { BackendOfflineState, Button, EmptyState, ErrorState, FormField, LoadingState, Modal, Pagination, SearchInput, StatusBadge } from "@/src/components/ui/ui";
import { TelegramNotification, TelegramRecipient, TelegramSettingsData, TelegramStatus } from "./types";

const settingLabels: [keyof TelegramSettingsData, string, string][] = [
  ["enabled", "Telegram-уведомления", "Главный переключатель отправки уведомлений"],
  ["notifyOnHandoff", "Передача менеджеру", "AI передал диалог сотруднику"],
  ["notifyOnClientRequestedManager", "Клиент просит менеджера", "Клиент явно запросил человека"],
  ["notifyOnNewLead", "Новый лид", "Создан новый лид"],
  ["notifyOnQualifiedLead", "Лид квалифицирован", "Клиент подтвердил интерес"],
  ["notifyOnAiUncertain", "AI не уверен", "Ответ требует внимания менеджера"],
  ["notifyOnAiFailure", "Ошибка AI", "Не удалось получить ответ модели"],
  ["notifyOnWhatsAppFailure", "Ошибка WhatsApp", "Сообщение не удалось обработать"],
  ["notifyOnMediaFailure", "Ошибка медиа", "Не удалось обработать вложение"],
  ["notifyOnAutomationFailure", "Ошибка автоматизации", "Сценарий завершился с ошибкой"],
  ["notifyOnSystemError", "Системная ошибка", "Критическая ошибка сервиса"],
];

const typeLabels: Record<string,string> = { HANDOFF:"Передача менеджеру", CLIENT_REQUESTED_MANAGER:"Клиент просит менеджера", NEW_LEAD:"Новый лид", QUALIFIED_LEAD:"Лид квалифицирован", AI_UNCERTAIN:"AI не уверен", AI_FAILURE:"Ошибка AI", WHATSAPP_FAILURE:"Ошибка WhatsApp", MEDIA_FAILURE:"Ошибка медиа", AUTOMATION_FAILURE:"Ошибка автоматизации", SYSTEM_ERROR:"Системная ошибка" };
const statusLabels: Record<string,string> = { SENT:"Отправлено", DELIVERED:"Доставлено", FAILED:"Ошибка", PENDING:"Ожидает", SKIPPED:"Пропущено" };

export function TelegramSettings() {
  const [status,setStatus]=useState<TelegramStatus>(); const [recipients,setRecipients]=useState<TelegramRecipient[]>([]); const [settings,setSettings]=useState<TelegramSettingsData>();
  const [loading,setLoading]=useState(true); const [offline,setOffline]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const [connectOpen,setConnectOpen]=useState(false); const [disableTarget,setDisableTarget]=useState<TelegramRecipient|null>(null); const [name,setName]=useState(""); const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [s,r,c]=await Promise.all([api.get<TelegramStatus>("/telegram/status"),api.get<unknown>("/telegram/recipients"),api.get<TelegramSettingsData>("/telegram/settings")]);setStatus(s);setRecipients(unpackList<TelegramRecipient>(r).items);setSettings(c);setOffline(false)}catch(e){setOffline(e instanceof ApiError&&e.status===0);setError(message(e))}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load]);
  function flash(text:string){setNotice(text);setTimeout(()=>setNotice(""),3000)}
  async function create(){if(!name.trim())return;setBusy("create");setError("");try{const result=await api.post<Record<string,unknown>>("/telegram/recipients",{name:name.trim()});const connectUrl=String(result.connectUrl||result.connectionUrl||result.url||"");setConnectOpen(false);setName("");await load();if(connectUrl){window.open(connectUrl,"_blank","noopener,noreferrer");flash("Ссылка подключения открыта в новой вкладке")}else flash("Получатель создан")}catch(e){setError(message(e))}finally{setBusy("")}}
  async function recipientAction(item:TelegramRecipient,action:"test"|"reconnect"|"disable"){setBusy(`${action}:${item.id}`);setError("");try{const result=await api.post<Record<string,unknown>>(`/telegram/recipients/${item.id}/${action}`);if(action==="reconnect"){const url=String(result?.connectUrl||result?.connectionUrl||result?.url||"");if(url)window.open(url,"_blank","noopener,noreferrer")}flash(action==="test"?"Тестовое уведомление отправлено":action==="disable"?"Получатель отключён":"Ссылка для переподключения открыта");setDisableTarget(null);await load()}catch(e){setError(message(e))}finally{setBusy("")}}
  async function toggle(key:keyof TelegramSettingsData,value:boolean){if(!settings)return;const previous=settings;setSettings({...settings,[key]:value});setBusy(`setting:${String(key)}`);try{const updated=await api.patch<TelegramSettingsData>("/telegram/settings",{[key]:value});setSettings(updated);flash("Настройки сохранены")}catch(e){setSettings(previous);setError(message(e))}finally{setBusy("")}}
  if(loading&&!status)return <section className="page"><LoadingState/></section>; if(offline)return <section className="page"><BackendOfflineState retry={load}/></section>;
  return <section className="page telegram-page">
    <div className="page-intro"><div><h2>Telegram</h2><p>Подключение менеджеров и уведомления о важных событиях</p></div><Button variant="secondary" onClick={load} loading={loading}><RefreshCw size={15}/>Обновить</Button></div>
    {notice&&<div className="toast-inline">{notice}</div>}{error&&<ErrorState message={error} retry={load}/>} 
    {status&&<article className="telegram-status panel"><div className={`telegram-logo ${status.botReachable?"ready":"failed"}`}><Bot/></div><div><div className="heading-line"><h3>Telegram-бот</h3><StatusBadge tone={status.botReachable?"success":"danger"}>{status.botReachable?"Доступен":"Недоступен"}</StatusBadge></div><p>{status.configured?"Бот настроен и готов отправлять уведомления.":"Бот ещё не настроен на сервере."}</p><div className="telegram-facts"><span>Сервис <b>{status.enabled?"включён":"выключен"}</b></span><span>Подключено получателей <b>{status.connectedRecipients}</b></span><span>Основной получатель <b>{status.primaryRecipientConnected?"подключён":"не подключён"}</b></span></div></div></article>}
    <div className="telegram-section-head"><div><h3>Получатели</h3><p>Менеджеры, которым бот отправляет уведомления</p></div><Button onClick={()=>setConnectOpen(true)} disabled={!status?.configured}><UserRoundPlus size={16}/>Подключить получателя</Button></div>
    {!recipients.length?<div className="panel"><EmptyState title="Получателей пока нет" description="Подключите менеджера, чтобы начать получать уведомления в Telegram."/></div>:<div className="recipient-grid">{recipients.map(item=><RecipientCard key={item.id} item={item} busy={busy} onAction={recipientAction} onDisable={setDisableTarget}/>)}</div>}
    {settings&&<article className="panel notification-settings"><div className="section-icon"><Bell/></div><div className="telegram-section-head"><div><h3>Какие уведомления отправлять</h3><p>Изменения сохраняются сразу</p></div></div><div className="switch-list">{settingLabels.map(([key,label,help],index)=><label className={`switch-row ${index===0?"master":""}`} key={String(key)}><span><b>{label}</b><small>{help}</small></span><input type="checkbox" checked={Boolean(settings[key])} disabled={busy===`setting:${String(key)}`||(key!=="enabled"&&!settings.enabled)} onChange={e=>toggle(key,e.target.checked)}/><i/></label>)}</div></article>}
    <NotificationHistory/>
    <Modal open={connectOpen} title="Подключить получателя" onClose={()=>!busy&&setConnectOpen(false)}><p>Укажите понятное имя. После создания откроется Telegram — менеджеру останется нажать Start.</p><FormField label="Имя получателя" placeholder="Например, Основной менеджер" autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&create()}/><div className="form-actions"><Button variant="secondary" onClick={()=>setConnectOpen(false)} disabled={!!busy}>Отмена</Button><Button loading={busy==="create"} disabled={!name.trim()} onClick={create}><ExternalLink size={15}/>Создать и открыть Telegram</Button></div></Modal>
    <Modal open={!!disableTarget} title="Отключить получателя?" onClose={()=>!busy&&setDisableTarget(null)}><p>Уведомления этому менеджеру больше не будут отправляться. Подключение можно будет создать повторно.</p><div className="form-actions"><Button variant="secondary" disabled={!!busy} onClick={()=>setDisableTarget(null)}>Отмена</Button><Button variant="danger" loading={busy===`disable:${disableTarget?.id}`} onClick={()=>disableTarget&&recipientAction(disableTarget,"disable")}>Отключить</Button></div></Modal>
  </section>
}

function RecipientCard({item,busy,onAction,onDisable}:{item:TelegramRecipient;busy:string;onAction:(i:TelegramRecipient,a:"test"|"reconnect"|"disable")=>void;onDisable:(i:TelegramRecipient)=>void}){const connected=item.connected===true||["CONNECTED","ACTIVE"].includes(String(item.status));const username=item.telegramUsername||item.username;return <article className="panel recipient-card"><div className="recipient-head"><div className="recipient-avatar"><MessageCircle/></div><div><h3>{item.name||"Получатель Telegram"}</h3><StatusBadge tone={connected?"success":item.enabled===false?"neutral":"warning"}>{item.enabled===false?"Отключён":connected?"Подключён":"Ожидает подключения"}</StatusBadge></div></div>{username&&<p className="recipient-username">@{String(username).replace(/^@/,"")}</p>}<p className="muted">{connected?`Подключён ${dateTime(item.connectedAt||item.updatedAt)}`:"Откройте ссылку подключения и запустите бота."}</p><div className="recipient-actions"><Button variant="secondary" loading={busy===`test:${item.id}`} disabled={!connected||!!busy} onClick={()=>onAction(item,"test")}><Send size={15}/>Тест</Button><Button variant="secondary" loading={busy===`reconnect:${item.id}`} disabled={!!busy} onClick={()=>onAction(item,"reconnect")}><RotateCcw size={15}/>Переподключить</Button><Button variant="danger" disabled={!!busy||item.enabled===false} onClick={()=>onDisable(item)}><Unplug size={15}/>Отключить</Button></div></article>}

function NotificationHistory(){const [items,setItems]=useState<TelegramNotification[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [detail,setDetail]=useState<TelegramNotification|null>(null);const limit=20;const load=useCallback(async()=>{setLoading(true);try{const result=unpackList<TelegramNotification>(await api.get("/telegram/notifications",{query:{page,limit,search}}));setItems(result.items);setTotal(result.total);setError("")}catch(e){setError(message(e))}finally{setLoading(false)}},[page,search]);useEffect(()=>{const timer=setTimeout(load,search?350:0);return()=>clearTimeout(timer)},[load,search]);const rows=useMemo(()=>items,[items]);return <article className="panel notification-history"><div className="telegram-section-head"><div><h3>История уведомлений</h3><p>Последние попытки отправки через Telegram</p></div><SearchInput placeholder="Поиск по уведомлениям…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div>{loading&&!items.length?<LoadingState/>:error?<ErrorState message={error} retry={load}/>:!rows.length?<EmptyState title={search?"Ничего не найдено":"Уведомлений пока нет"} description="Здесь появится история после первой отправки."/>:<><div className="table-wrap"><table><thead><tr><th>Событие</th><th>Сообщение</th><th>Результат</th><th>Дата</th></tr></thead><tbody>{rows.map((item,index)=><tr key={item.id||index} className="clickable-row" onClick={()=>setDetail(item)}><td>{typeLabels[String(item.type)]||human(item.type)||"Уведомление"}</td><td>{short(item.title||item.message)}</td><td><StatusBadge tone={String(item.status)==="FAILED"?"danger":String(item.status)==="SENT"||String(item.status)==="DELIVERED"?"success":"neutral"}>{statusLabels[String(item.status)]||human(item.status)||"—"}</StatusBadge></td><td>{dateTime(item.createdAt)}</td></tr>)}</tbody></table></div><Pagination page={page} total={total} limit={limit} onChange={setPage}/></>}<Modal open={!!detail} title="Уведомление" onClose={()=>setDetail(null)}>{detail&&<div className="notification-detail"><Detail label="Событие" value={typeLabels[String(detail.type)]||human(detail.type)}/><Detail label="Статус" value={statusLabels[String(detail.status)]||human(detail.status)}/><Detail label="Дата" value={dateTime(detail.createdAt)}/><Detail label="Заголовок" value={detail.title}/><Detail label="Сообщение" value={detail.message}/>{detail.error&&<Detail label="Причина ошибки" value={detail.error}/>}</div>}</Modal></article>}
function Detail({label,value}:{label:string;value:unknown}){if(value===undefined||value===null||value==="")return null;return <div className="detail-row"><span>{label}</span><p>{String(value)}</p></div>}
function message(e:unknown){return e instanceof Error?e.message:"Не удалось выполнить операцию"} function short(v:unknown){const s=human(v)||"—";return s.length>90?`${s.slice(0,90)}…`:s} function human(v:unknown){if(v===undefined||v===null)return "";return String(v).replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase())}
