"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { ArrowLeft,Pause,Play,RotateCcw,XCircle } from "lucide-react";
import { api,ApiError,unpackList } from "@/src/lib/api/client";
import { dateTime,safe } from "@/src/lib/formatters";
import { CAMPAIGN_TARGET_STATUS_LABELS,STRATEGY_LABELS,fieldValueLabel } from "@/src/lib/constants/labels";
import { Button,EmptyState,ErrorState,FormField,LoadingState,Pagination,SearchInput,SelectFilter,StatusBadge } from "@/src/components/ui/ui";
import { Campaign,CampaignTarget } from "./types";
import { metric,tone } from "./campaigns-page";

type Tab="overview"|"targets"|"settings";
export type PreflightIssue={code?:string;key?:string;message?:string;ready?:boolean;label?:string};
export type Preflight=Record<string,unknown>&{ready:boolean;checks?:PreflightIssue[];issues?:PreflightIssue[]};
export function CampaignDetail({id}:{id:string}){
 const[campaign,setCampaign]=useState<Campaign>(),[preflight,setPreflight]=useState<Preflight>(),[tab,setTab]=useState<Tab>("overview"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const value=await api.get<Campaign>(`/campaigns/${id}`);setCampaign(value);if(["DRAFT","SCHEDULED"].includes(value.status))setPreflight(await api.get<Preflight>(`/campaigns/${id}/preflight`));else setPreflight(undefined);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить кампанию")}finally{if(!silent)setLoading(false)}},[id]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const campaignStatus=campaign?.status;
 useEffect(()=>{if(!campaignStatus||!["RUNNING","PAUSED"].includes(campaignStatus))return;const timer=setInterval(()=>void load(true),campaignStatus==="RUNNING"?5000:15000);return()=>clearInterval(timer)},[campaignStatus,load]);
 async function action(name:"start"|"pause"|"resume"|"cancel"){if(busy)return;setBusy(true);setError("");try{setCampaign(await api.post<Campaign>(`/campaigns/${id}/${name}`));await load(true)}catch(e){setError(startError(e))}finally{setBusy(false)}}
 if(loading&&!campaign)return <LoadingState/>;if(!campaign)return <section className="page"><ErrorState message={error} retry={()=>load()}/></section>;
 return <section className="page"><Link className="back-link" href="/campaigns"><ArrowLeft size={15}/>Все кампании</Link><header className="campaign-heading"><div><div className="heading-line"><h2>{campaign.name}</h2><StatusBadge tone={tone(campaign.status)}>{fieldValueLabel("status",campaign.status,"campaign")}</StatusBadge></div><p>{campaign.description||"Описание не указано"}</p></div><div className="lifecycle">{["DRAFT","SCHEDULED"].includes(campaign.status)&&<Button loading={busy} disabled={!preflight?.ready} onClick={()=>action("start")}><Play size={15}/>Запустить</Button>}{campaign.status==="RUNNING"&&<Button loading={busy} onClick={()=>action("pause")}><Pause size={15}/>Приостановить</Button>}{campaign.status==="PAUSED"&&<Button loading={busy} onClick={()=>action("resume")}><RotateCcw size={15}/>Продолжить</Button>}{["DRAFT","SCHEDULED","RUNNING","PAUSED"].includes(campaign.status)&&<Button variant="danger" disabled={busy} onClick={()=>action("cancel")}><XCircle size={15}/>Отменить</Button>}</div></header>{campaign.status==="PAUSED"&&<p className="notice">Новые сообщения временно не отправляются</p>}{error&&<ErrorState message={error} retry={()=>load()}/>}<Metrics campaign={campaign}/>{preflight&&<PreflightPanel value={preflight}/>}<div className="tabs">{([["overview","Обзор"],["targets","Контакты"],["settings","Настройки"]] as [Tab,string][]).map(([key,label])=><button type="button" className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}>{label}</button>)}</div>{tab==="overview"&&<Overview campaign={campaign}/>} {tab==="targets"&&<Targets campaignId={id} campaignStatus={campaign.status}/>} {tab==="settings"&&<Settings campaign={campaign} onSaved={setCampaign}/>}</section>;
}
export function preflightItems(value:Preflight){return value.checks||value.issues||[]}
function PreflightPanel({value}:{value:Preflight}){const items=preflightItems(value);return <article className="panel preflight-panel"><h3>Готовность к запуску</h3><p className={value.ready?"success-text":"form-error"}>{value.ready?"Все проверки пройдены":"Нужно завершить настройку"}</p><div className="preflight-list">{items.map((item,index)=><div className={item.ready===false?"blocked":"ready"} key={item.code||item.key||index}><span>{item.ready===false?"✕":"✓"}</span><p>{item.message||item.label||"Проверка"}</p>{item.ready===false&&<IssueAction code={String(item.code||item.key||"")}/>}</div>)}</div></article>}
function IssueAction({code}:{code:string}){const value=code.toUpperCase();if(value.includes("WHATSAPP"))return <Link href="/whatsapp">Перейти в WhatsApp</Link>;if(value.includes("STRATEG"))return <Link href="/prompt-strategies">Настроить стратегию</Link>;if(value.includes("AUTOMATION")||value.includes("SETTING"))return <Link href="/settings">Открыть настройки</Link>;if(value.includes("CONTACT"))return <Link href="/campaigns">Изменить кампанию</Link>;return null}
function Metrics({campaign}:{campaign:Campaign}){return <div className="campaign-metrics"><Metric label="Выбрано" value={metric(campaign,"selectedCount")}/><Metric label="Обработано" value={metric(campaign,"processedCount")}/><Metric label="Ответили" value={metric(campaign,"repliedCount")}/><Metric label="Лиды" value={metric(campaign,"leadCount")}/><Metric label="Передано менеджеру" value={metric(campaign,"handoffCount")}/><Metric label="Ошибки" value={Number(campaign.errorCount||0)}/></div>}
function Metric({label,value}:{label:string;value:unknown}){return <article><span>{label}</span><strong>{typeof value==="number"?value:"—"}</strong></article>}
function Overview({campaign}:{campaign:Campaign}){const strategy=String(campaign.strategyCode||campaign.filters?.strategyCode||"");return <article className="panel"><h3>Состояние кампании</h3><dl className="facts"><dt>Источник</dt><dd>{campaign.sourceType==="IMPORT_JOB"?"Импортированная база":"Все контакты"}</dd><dt>Стратегия</dt><dd>{strategy?STRATEGY_LABELS[strategy]||"Стратегия":"Не назначена"}</dd><dt>Создана</dt><dd>{dateTime(campaign.createdAt)}</dd><dt>Обновлена</dt><dd>{dateTime(campaign.updatedAt)}</dd></dl></article>}
function Targets({campaignId,campaignStatus}:{campaignId:string;campaignStatus:string}){const[items,setItems]=useState<CampaignTarget[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[status,setStatus]=useState(""),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{const result=unpackList<CampaignTarget>(await api.get(`/campaigns/${campaignId}/targets`,{query:{page,limit:20,status,search}}));setItems(result.items);setTotal(result.total);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить контакты")}finally{setLoading(false)}},[campaignId,page,status,search]);useEffect(()=>{const t=setTimeout(()=>void load(),search?350:0);return()=>clearTimeout(t)},[load,search]);useEffect(()=>{if(campaignStatus!=="RUNNING")return;const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[campaignStatus,load]);if(loading&&!items.length)return <LoadingState/>;return <article className="panel"><div className="toolbar"><SearchInput value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Компания или телефон…"/><SelectFilter label="Статус" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Все</option>{Object.entries(CAMPAIGN_TARGET_STATUS_LABELS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</SelectFilter></div>{error?<ErrorState message={error} retry={load}/>:!items.length?<EmptyState title="Контактов нет"/>:<><div className="table-wrap"><table><thead><tr><th>Компания</th><th>Телефон</th><th>Стратегия</th><th>Статус</th><th>Отправлено</th><th>Ошибка</th></tr></thead><tbody>{items.map(target=>{const contact=target.contact||{},code=String(target.strategyCode||contact.strategyCode||"");return <tr key={target.id}><td>{safe(contact.companyName)}</td><td>{safe(contact.phone)}</td><td>{STRATEGY_LABELS[code]||"Не назначена"}</td><td><StatusBadge>{fieldValueLabel("status",target.status,"campaignTarget")}</StatusBadge></td><td>{dateTime(target.messageSentAt)}</td><td>{publicError(target.errorMessage)}</td></tr>})}</tbody></table></div><Pagination page={page} total={total} limit={20} onChange={setPage}/></>}</article>}
function Settings({campaign,onSaved}:{campaign:Campaign;onSaved:(x:Campaign)=>void}){const editable=["DRAFT","PAUSED"].includes(campaign.status),[settings,setSettings]=useState(campaign.settings||{workingHoursStart:"09:00",workingHoursEnd:"18:00",dailyMessageLimit:100,minDelaySeconds:60,maxDelaySeconds:180,timezone:"Asia/Almaty"}),[busy,setBusy]=useState(false),[error,setError]=useState("");async function save(){setBusy(true);try{onSaved(await api.patch<Campaign>(`/campaigns/${campaign.id}`,{settings}));setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить настройки")}finally{setBusy(false)}}return <article className="panel"><h3>Настройки отправки</h3><div className="filter-grid"><FormField label="Начало рабочего времени" type="time" disabled={!editable} value={settings.workingHoursStart} onChange={e=>setSettings({...settings,workingHoursStart:e.target.value})}/><FormField label="Конец рабочего времени" type="time" disabled={!editable} value={settings.workingHoursEnd} onChange={e=>setSettings({...settings,workingHoursEnd:e.target.value})}/><FormField label="Дневной лимит" type="number" disabled={!editable} value={settings.dailyMessageLimit} onChange={e=>setSettings({...settings,dailyMessageLimit:Number(e.target.value)})}/><FormField label="Часовой пояс" disabled={!editable} value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></div>{error&&<p className="form-error">{error}</p>}{editable&&<Button loading={busy} onClick={save}>Сохранить настройки</Button>}</article>}
function startError(error:unknown){if(error instanceof ApiError){const details=error.details as {issues?:Array<{message?:string}>}|undefined;const issues=details?.issues?.map(x=>x.message).filter(Boolean);return issues?.length?issues.join(". "):error.message}return "Операция не выполнена"}
function publicError(value:unknown){if(typeof value!=="string"||!value)return "—";if(/prisma|stack|openai| at |exception/i.test(value))return "Не удалось обработать контакт";return value}
