"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { api, ApiError, unpackList } from "@/src/lib/api/client";
import { BUSINESS_TYPE_LABELS, CRM_PROVIDER_LABELS, STRATEGY_LABELS } from "@/src/lib/constants/labels";
import { Button, FormField, LoadingState, Modal, SelectFilter, TextAreaField } from "@/src/components/ui/ui";
import { Campaign, CampaignDraft } from "./types";
import { campaignSource } from "./campaign-model";

type ImportJob=Record<string,unknown>&{id?:string;importId?:string;fileName?:string;createdAt?:string;validRows?:number;importedRows?:number;status?:string};
const initial:CampaignDraft={name:"",description:"",sourceType:"ALL_CONTACTS",importId:"",filters:{outreachEligible:true},settings:{workingHoursStart:"09:00",workingHoursEnd:"18:00",dailyMessageLimit:100,minDelaySeconds:60,maxDelaySeconds:180,timezone:"Asia/Almaty"}};
export function CampaignWizard({open,onClose}:{open:boolean;onClose:()=>void}){
 const router=useRouter(),[step,setStep]=useState(1),[draft,setDraft]=useState(initial),[imports,setImports]=useState<ImportJob[]>([]),[loadingImports,setLoadingImports]=useState(false),[preview,setPreview]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const loadImports=useCallback(async()=>{setLoadingImports(true);try{const result=unpackList<ImportJob>(await api.get("/imports",{query:{page:1,limit:100,status:"COMPLETED"}}));setImports(result.items);const requested=new URLSearchParams(location.search).get("importId");if(requested)setDraft(current=>({...current,sourceType:"IMPORT_JOB",importId:requested}))}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить импорты")}finally{setLoadingImports(false)}},[]);
 useEffect(()=>{if(!open)return;const timer=setTimeout(()=>void loadImports(),0);return()=>clearTimeout(timer)},[open,loadImports]);
 const count=Number(preview?.count??preview?.total??preview?.selectedCount??0);
 function filter(key:keyof CampaignDraft["filters"],value:string){setDraft(current=>({...current,filters:{...current.filters,[key]:value||undefined}}));setPreview(null)}
 async function loadPreview(){setBusy(true);setError("");try{setPreview(await api.post<Record<string,unknown>>("/campaigns/preview-targets",campaignSource(draft.sourceType,draft.importId,draft.filters)));setStep(4)}catch(e){setError(e instanceof ApiError?e.message:"Не удалось проверить контакты")}finally{setBusy(false)}}
 async function create(){setBusy(true);setError("");try{const campaign=await api.post<Campaign>("/campaigns",{name:draft.name,description:draft.description||undefined,...campaignSource(draft.sourceType,draft.importId,draft.filters),settings:draft.settings});onClose();router.push(`/campaigns/${campaign.id}`)}catch(e){setError(e instanceof ApiError?e.message:"Не удалось создать кампанию")}finally{setBusy(false)}}
 return <Modal open={open} title="Создание кампании" onClose={()=>!busy&&onClose()}><div className="wizard-progress">{["Основное","Источник","Условия","Предпросмотр","Настройки"].map((x,i)=><div className={step>=i+1?"done":""} key={x}><span>{i+1}</span><small>{x}</small></div>)}</div>{error&&<p className="form-error">{error}</p>}
 {step===1&&<div className="wizard-body"><FormField label="Название кампании" required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><TextAreaField label="Описание" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div>}
 {step===2&&<div className="wizard-body"><SelectFilter label="Источник контактов" value={draft.sourceType} onChange={e=>setDraft({...draft,sourceType:e.target.value as CampaignDraft["sourceType"],importId:e.target.value==="ALL_CONTACTS"?"":draft.importId})}><option value="ALL_CONTACTS">Все контакты</option><option value="IMPORT_JOB">Конкретный импорт</option></SelectFilter>{draft.sourceType==="IMPORT_JOB"&&(loadingImports?<LoadingState/>:<SelectFilter label="Импорт" value={draft.importId} onChange={e=>setDraft({...draft,importId:e.target.value})}><option value="">Выберите импорт</option>{imports.map(item=>{const id=String(item.id||item.importId),count=Number(item.importedRows||item.validRows||0);return <option value={id} key={id}>{item.fileName||"Импорт"} · {formatDate(item.createdAt)} · {count} контактов</option>})}</SelectFilter>)}</div>}
 {step===3&&<div className="wizard-body filter-grid"><Filter label="Тип бизнеса" value={draft.filters.businessType} options={BUSINESS_TYPE_LABELS} onChange={x=>filter("businessType",x)}/><Filter label="CRM" value={draft.filters.crmProvider} options={CRM_PROVIDER_LABELS} onChange={x=>filter("crmProvider",x)}/><Filter label="Стратегия" value={draft.filters.strategyCode} options={STRATEGY_LABELS} onChange={x=>filter("strategyCode",x)}/><FormField label="Город" value={draft.filters.city||""} onChange={e=>filter("city",e.target.value)}/></div>}
 {step===4&&<div className="campaign-preview"><h3>Предпросмотр</h3><dl className="facts"><dt>Выбрано контактов</dt><dd>{count}</dd><dt>Тип бизнеса</dt><dd>{label(BUSINESS_TYPE_LABELS,draft.filters.businessType)}</dd><dt>CRM</dt><dd>{label(CRM_PROVIDER_LABELS,draft.filters.crmProvider)}</dd><dt>Стратегия</dt><dd>{label(STRATEGY_LABELS,draft.filters.strategyCode)}</dd><dt>Город</dt><dd>{draft.filters.city||"Все города"}</dd><dt>Источник</dt><dd>{draft.sourceType==="IMPORT_JOB"?selectedImport(imports,draft.importId)?.fileName||"Выбранный импорт":"Все контакты"}</dd></dl>{count===0&&<p className="form-error">По выбранным условиям контакты не найдены.</p>}</div>}
 {step===5&&<div className="wizard-body filter-grid"><FormField label="Начало рабочего времени" type="time" value={draft.settings.workingHoursStart} onChange={e=>setDraft({...draft,settings:{...draft.settings,workingHoursStart:e.target.value}})}/><FormField label="Конец рабочего времени" type="time" value={draft.settings.workingHoursEnd} onChange={e=>setDraft({...draft,settings:{...draft.settings,workingHoursEnd:e.target.value}})}/><FormField label="Лимит в день" type="number" min={1} value={draft.settings.dailyMessageLimit} onChange={e=>setDraft({...draft,settings:{...draft.settings,dailyMessageLimit:Number(e.target.value)}})}/><FormField label="Часовой пояс" value={draft.settings.timezone} onChange={e=>setDraft({...draft,settings:{...draft.settings,timezone:e.target.value}})}/><p className="notice full">Кампания будет создана как черновик и не запустится автоматически.</p></div>}
 <div className="wizard-actions">{step>1?<Button variant="secondary" disabled={busy} onClick={()=>setStep(x=>x-1)}><ArrowLeft size={15}/>Назад</Button>:<span/>}<span/>{step===1&&<Button disabled={!draft.name.trim()} onClick={()=>setStep(2)}>Далее<ArrowRight size={15}/></Button>}{step===2&&<Button disabled={draft.sourceType==="IMPORT_JOB"&&!draft.importId} onClick={()=>setStep(3)}>Далее<ArrowRight size={15}/></Button>}{step===3&&<Button loading={busy} onClick={loadPreview}>Проверить контакты</Button>}{step===4&&<Button disabled={count===0} onClick={()=>setStep(5)}>Далее<ArrowRight size={15}/></Button>}{step===5&&<Button loading={busy} onClick={create}>Создать черновик</Button>}</div></Modal>;
}
function Filter({label:caption,value,options,onChange}:{label:string;value?:string;options:Record<string,string>;onChange:(x:string)=>void}){return <SelectFilter label={caption} value={value||""} onChange={e=>onChange(e.target.value)}><option value="">Все</option>{Object.entries(options).map(([key,text])=><option value={key} key={key}>{text}</option>)}</SelectFilter>}
function label(labels:Record<string,string>,value?:string){return value?labels[value]||value:"Не выбрано"}
function formatDate(value?:string){return value?new Date(value).toLocaleDateString("ru-RU"):"дата не указана"}
function selectedImport(items:ImportJob[],id:string){return items.find(x=>String(x.id||x.importId)===id)}
