"use client";

import Link from "next/link";
import { ChangeEvent, DragEvent, useCallback, useEffect, useState } from "react";
import { CheckCircle2, FileSpreadsheet, RotateCcw, UploadCloud, X } from "lucide-react";
import { api, ApiError, unpackList } from "@/src/lib/api/client";
import { Button, EmptyState, ErrorState, HumanData, LoadingState, Pagination, StatusBadge } from "@/src/components/ui/ui";
import { fieldValueLabel } from "@/src/lib/constants/labels";
import { Entity } from "@/src/types";
import { canConfirmMapping, IMPORT_FIELDS, importCampaignHref, ImportMapping, missingRequiredMapping, summaryNumber } from "./import-model";

export function ImportWizard() {
  const [file,setFile]=useState<File|null>(null),[job,setJob]=useState<Entity|null>(null),[mapping,setMapping]=useState<ImportMapping>({}),[rows,setRows]=useState<Entity[]>([]),[imports,setImports]=useState<Entity[]>([]);
  const [importId,setImportId]=useState(""),[step,setStep]=useState(1),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[loadingHistory,setLoadingHistory]=useState(true),[error,setError]=useState(""),[historyError,setHistoryError]=useState(""),[inputKey,setInputKey]=useState(0);
  const loadHistory=useCallback(async()=>{setLoadingHistory(true);try{setImports(unpackList<Entity>(await api.get("/imports",{query:{page:1,limit:50}})).items);setHistoryError("")}catch(e){setHistoryError(e instanceof Error?e.message:"Не удалось загрузить историю импортов")}finally{setLoadingHistory(false)}},[]);
  const openImport=useCallback(async(id:string)=>{setBusy(true);setError("");try{const value=await api.get<Entity>(`/imports/${id}`);setImportId(id);setJob(value);setMapping(readMapping(value));setStep(isCompleted(value)?4:2);history.replaceState(null,"",`/imports?importId=${encodeURIComponent(id)}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось открыть импорт")}finally{setBusy(false)}},[]);
  useEffect(()=>{const timer=setTimeout(()=>{void loadHistory();const id=new URLSearchParams(location.search).get("importId")||localStorage.getItem("zapis-import-id");if(id)void openImport(id)},0);return()=>clearTimeout(timer)},[loadHistory,openImport]);
  function choose(next?:File){setError("");if(!next)return;if(next.size>10*1024*1024)return setError("Размер файла превышает 10 МБ");if(!/\.(xlsx?|csv)$/i.test(next.name))return setError("Поддерживаются XLS, XLSX и CSV");setFile(next)}
  async function analyze(){if(!file)return;setBusy(true);setError("");try{const form=new FormData();form.append("file",file);const value=await api.post<Entity>("/imports/preview",form),id=String(value.importId||value.id||"");if(!id)throw new ApiError("Сервер не вернул идентификатор импорта",0,value);setImportId(id);setJob(value);setMapping(readMapping(value));setStep(2);localStorage.setItem("zapis-import-id",id);history.replaceState(null,"",`/imports?importId=${encodeURIComponent(id)}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось проанализировать файл")}finally{setBusy(false)}}
  async function recalculate(){if(!canConfirmMapping(mapping))return;setBusy(true);setError("");try{const value=await api.patch<Entity>(`/imports/${importId}/mapping`,{mapping});setJob(value);setMapping(readMapping(value));await loadRows(1,value)}catch(e){setError(e instanceof Error?e.message:"Не удалось пересчитать импорт")}finally{setBusy(false)}}
  async function loadRows(next=page,current=job){setBusy(true);try{const payload=await api.get(`/imports/${importId}/rows`,{query:{page:next,limit:20}});setRows(unpackList<Entity>(payload).items);setJob(current||await api.get<Entity>(`/imports/${importId}`));setPage(next);setStep(3)}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить строки")}finally{setBusy(false)}}
  async function confirm(){setBusy(true);setError("");try{const value=await api.post<Entity>(`/imports/${importId}/confirm`);setJob(value);setStep(4);localStorage.removeItem("zapis-import-id");history.replaceState(null,"","/imports");await loadHistory()}catch(e){setError(e instanceof Error?e.message:"Не удалось завершить импорт")}finally{setBusy(false)}}
  function reset(){setFile(null);setJob(null);setMapping({});setRows([]);setImportId("");setStep(1);setPage(1);setError("");setInputKey(x=>x+1);localStorage.removeItem("zapis-import-id");history.replaceState(null,"","/imports")}
  const missing=missingRequiredMapping(mapping), columns=list(job,"detectedColumns");
  return <section className="page imports-page">
    <div className="page-intro"><div><h2>Импорт базы</h2><p>Загрузите таблицу, проверьте колонки и импортируйте корректные контакты.</p></div><Button variant="secondary" onClick={reset} disabled={busy}><RotateCcw size={15}/>Новый импорт</Button></div>
    <div className="steps">{["Файл","Сопоставление","Проверка","Готово"].map((label,index)=><div className={step>=index+1?"done":""} key={label}><span>{step>index+1?<CheckCircle2 size={18}/>:index+1}</span>{label}</div>)}</div>
    {error&&<ErrorState message={error}/>}
    {step===1&&<div className="upload" onDragOver={e=>e.preventDefault()} onDrop={(e:DragEvent)=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><UploadCloud size={38}/><h2>Перетащите таблицу сюда</h2><p>XLS, XLSX или CSV, до 10 МБ</p><label className="button secondary">Выбрать файл<input key={inputKey} hidden type="file" accept=".xls,.xlsx,.csv" onChange={(e:ChangeEvent<HTMLInputElement>)=>choose(e.target.files?.[0])}/></label>{file&&<div className="chosen"><FileSpreadsheet/><div><b>{file.name}</b><span>{(file.size/1024).toFixed(1)} КБ</span></div><button onClick={()=>setFile(null)} aria-label="Убрать файл"><X/></button></div>}<Button disabled={!file} loading={busy} onClick={analyze}>Проанализировать файл</Button></div>}
    {step===2&&<article className="panel"><h2>Сопоставление колонок</h2><p className="muted">Выберите назначение каждой колонки Excel. Компания и телефон обязательны.</p><div className="mapping-editor">{columns.map(source=><label className="mapping-row" key={source}><span>{source}</span><select value={mapping[source]||""} onChange={e=>setMapping(current=>({...current,[source]:e.target.value}))}>{IMPORT_FIELDS.map(([value,label])=><option value={value} key={value||"ignore"}>{label}</option>)}</select></label>)}</div>{missing.companyName&&<p className="form-error">Укажите колонку с названием компании</p>}{missing.phone&&<p className="form-error">Укажите колонку с телефоном</p>}{list(job,"ambiguousColumns").length>0&&<Notice title="Нужно проверить" values={list(job,"ambiguousColumns")}/>} {list(job,"unmappedColumns").length>0&&<Notice title="Не распознано" values={list(job,"unmappedColumns")}/>}<Button loading={busy} disabled={!canConfirmMapping(mapping)} onClick={recalculate}>Пересчитать</Button></article>}
    {step===3&&<article className="panel"><h2>Проверка импорта</h2><ImportSummary value={job}/>{rows.length>0&&<><div className="table-wrap"><table><thead><tr><th>Статус</th><th>Данные контакта</th><th>Ошибки</th></tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id||index)}><td>{fieldValueLabel("status",row.status,"import")}</td><td><HumanData value={row.normalizedData} context="import"/></td><td>{humanError(row.errors)}</td></tr>)}</tbody></table></div><Pagination page={page} total={summaryNumber(job,"total")} limit={20} onChange={loadRows}/></>}<div className="form-actions"><Button variant="secondary" onClick={()=>setStep(2)}>Назад</Button><Button loading={busy} onClick={confirm}>Импортировать корректные контакты</Button></div></article>}
    {step===4&&<div className="state success-state"><CheckCircle2/><h2>Импорт завершён</h2><p>Создано контактов: <b>{summaryNumber(job,"created","imported","valid")}</b></p><p>Дубликатов: <b>{summaryNumber(job,"duplicates","duplicateInFile","duplicate")}</b></p><p>Ошибок: <b>{summaryNumber(job,"errors","invalid")}</b></p><div className="form-actions"><Link className="button secondary" href="/contacts">Посмотреть контакты</Link><Link className="button primary" href={importCampaignHref(importId)}>Создать кампанию из этой базы</Link><Button variant="secondary" onClick={reset}>Импортировать ещё</Button></div></div>}
    <ImportHistory items={imports} loading={loadingHistory} error={historyError} open={openImport} retry={loadHistory}/>
  </section>;
}

function ImportHistory({items,loading,error,open,retry}:{items:Entity[];loading:boolean;error:string;open:(id:string)=>void;retry:()=>void}){return <article className="panel import-history"><h2>История импортов</h2>{loading?<LoadingState/>:error?<ErrorState message={error} retry={retry}/>:items.length===0?<EmptyState title="Импортов пока нет"/>:<div className="table-wrap"><table><thead><tr><th>Файл</th><th>Дата</th><th>Статус</th><th>Строк</th><th>Импортировано</th><th>Ошибок</th><th>Действия</th></tr></thead><tbody>{items.map(item=>{const id=String(item.id||item.importId);return <tr key={id}><td>{String(item.fileName||"Файл")}</td><td>{item.createdAt?new Date(String(item.createdAt)).toLocaleDateString("ru-RU"):"—"}</td><td><StatusBadge>{fieldValueLabel("status",item.status,"import")}</StatusBadge></td><td>{Number(item.totalRows||0)}</td><td>{Number(item.importedRows||item.validRows||0)}</td><td>{Number(item.invalidRows||0)}</td><td><button className="text-button" onClick={()=>open(id)}>Открыть</button> · <Link href={importCampaignHref(id)}>Создать кампанию</Link></td></tr>})}</tbody></table></div>}</article>}
function ImportSummary({value}:{value:Entity|null}){return <div className="campaign-metrics"><Metric label="Всего строк" value={summaryNumber(value,"total")}/><Metric label="Будет импортировано" value={summaryNumber(value,"valid","imported")}/><Metric label="Ошибок" value={summaryNumber(value,"invalid","errors")}/><Metric label="Дубликатов в файле" value={summaryNumber(value,"duplicateInFile")}/><Metric label="Уже есть в базе" value={summaryNumber(value,"duplicateInDatabase")}/></div>}
function Metric({label,value}:{label:string;value:number}){return <article><span>{label}</span><strong>{value}</strong></article>}
function Notice({title,values}:{title:string;values:string[]}){return <div className="notice"><b>{title}</b><p>{values.join(", ")}</p></div>}
function list(value:Entity|null,key:string){const item=value?.[key];return Array.isArray(item)?item.filter((x):x is string=>typeof x==="string"):[]}
function readMapping(value:Entity|null){const item=value?.mapping;if(!item||typeof item!=="object"||Array.isArray(item))return {};return Object.fromEntries(Object.entries(item).filter((entry):entry is [string,string]=>typeof entry[1]==="string"))}
function isCompleted(value:Entity|null){return ["COMPLETED","CONFIRMED","IMPORTED","DONE"].includes(String(value?.status||"").toUpperCase())}
function humanError(value:unknown){if(Array.isArray(value))return value.join("; ");return typeof value==="string"?value:"—"}
